### ISSUE TITLE
Copy type_name in every Tag might cost much memory

### ISSUE THREAD

**Issue by mudream4869** [SpockBotMC/cpp-nbt#3]
A constant string is copied in every tag. It might be a large cost in memory when reading a mca file.
https://github.com/SpockBotMC/cpp-nbt/blob/master/nbt/nbt.hpp#L73

**Comment by nickelpro** [comment]
My experience with NBT is entirely on the protocol side (where NBT is usually < a dozen tags), not actual Anvil files. I'd happily merge a commit that embeds names using a `std::string_view` or something similar. Or just move the names directly into the pretty printer, which is probably the correct answer. Though I somewhat like the convenience of being able to print a tag's identity directly without having to deference through an array or something.

**Comment by nickelpro** [comment]
Fixed in rewrite
