### ISSUE TITLE
it doesnt work... compiler errors out

### ISSUE THREAD

**Issue by AggamR** [SpockBotMC/cpp-nbt#4]
Hello! I'm tryna use your header file for a project, and the compiler spits 1000000 errors at me. I have simply used 
`#include "nbt.hpp"` in my code to check if it work.

**Comment by nickelpro** [comment]
Hey, what compiler are you using and what options are you passing it?

**Comment by test1230-lab** [comment]
https://pastebin.com/kD4FZYwY msvc debug x86

**Comment by test1230-lab** [comment]
https://i.imgur.com/aMzVR1i.png with latest cpp standard

**Comment by nickelpro** [comment]
> https://pastebin.com/kD4FZYwY msvc debug x86

Hi! As it says at the top of the ReadMe, this only compiles with GCC right now. MSVC doesn't support C++20 abbreviated function template syntax in any official release yet.

**Comment by test1230-lab** [comment]
Ok sorry, I must have missed it

**Comment by nickelpro** [comment]
This should now work with Visual Studio 16.9, which is still in pre-release but [all the code compiles on Godbolt](https://godbolt.org/z/d5oh8e).
