### ISSUE TITLE
tons of errors?

### ISSUE THREAD

**Issue by quebeh** [SpockBotMC/cpp-nbt#6]
i tried to compile with the header file, but it gives a ton of errors (over 750 lines) 
[errors.txt](https://github.com/SpockBotMC/cpp-nbt/files/8102291/errors.txt)

Im compiling with MinGW G++ 11.1.0.

**Comment by nickelpro** [comment]
As mentioned in the first line of the ReadMe, this is a C++20 library. The compiler and standard library you're using doesn't support concepts (The error message you posted tells you this if you read it) or abbreviated function templates.

I don't support MinGW directly in any case, you'll have to figure out if/when they intend to add support for C++20 features. Or you can use either of the supported Windows compilers (VS, clang).
